# Generated by Django 3.0.7 on 2020-06-29 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_meter', models.IntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('uuid', models.CharField(blank=True, max_length=200)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('ota_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
            ],
        ),
    ]
