# Generated by Django 3.0.7 on 2020-07-03 15:42

import device.models
from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('motor', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Motor')),
                ('Fuel', models.CharField(max_length=50, unique=True, verbose_name='Fuel')),
                ('Power', models.CharField(max_length=40)),
                ('Controller', models.CharField(max_length=10)),
                ('Type', models.CharField(blank=True, max_length=30)),
                ('Capacity', models.CharField(max_length=50)),
                ('image', stdimage.models.StdImageField(default='device/LogoSmart320.png', upload_to=device.models.get_file_path, verbose_name='Image')),
                ('year', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
        ),
    ]
