# Generated by Django 3.0.7 on 2020-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='Fuel',
            field=models.CharField(max_length=50, verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='motor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='tag',
            field=models.CharField(max_length=30),
        ),
    ]
