# Generated by Django 3.0.7 on 2020-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200703_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='function',
            field=models.CharField(blank=True, max_length=50, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='controller',
            field=models.CharField(max_length=30),
        ),
    ]
