# Generated by Django 3.0.7 on 2020-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200703_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='hour_meter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
