# Generated by Django 3.0.7 on 2020-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_motor_hour_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='oil_change',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
