# Generated by Django 3.0.7 on 2020-07-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_motor_oil_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motor', models.CharField(blank=True, max_length=50, verbose_name='Motor')),
                ('day', models.CharField(max_length=50, verbose_name='Consumption_day')),
                ('yesterday', models.CharField(max_length=40)),
            ],
        ),
    ]
