# Generated by Django 3.0.7 on 2020-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_motordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='motordata',
            name='operation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Operation'),
        ),
    ]
