# Generated by Django 3.0.7 on 2020-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Razão social')),
            ],
        ),
    ]
